### ISSUE TITLE
Segmentation Fault when training

### ISSUE THREAD

**Issue by brianbt** [zhengye1995/Zero-shot-Instance-Segmentation#23]
Hi,

I ran your code from *Install* up to *Training*, step by step.
When I try to run `./tools/dist_train.sh configs/zsi/65_15/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py 1`

```
2021-09-09 16:40:01,014 - INFO - Distributed training: True
~/Zero-shot-Instance-Segmentation/mmdet/models/anchor_heads/ba_anchor_head.py:108: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.vec_bg_weight = torch.tensor(self.vec_bg_weight).cuda().view([1, self.semantic_dims])
2021-09-09 16:40:05,295 - INFO - load model from: torchvision://resnet101
2021-09-09 16:40:05,712 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=9.95s)
creating index...
index created!
2021-09-09 16:40:17,039 - INFO - Start running, host: chan@GPU-TC1-08, work_dir: ~/Zero-shot-Instance-Segmentation/work_dirs/zsi/baseline/65_15
2021-09-09 16:40:17,039 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "~/.conda/envs/zsi/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "~/.conda/envs/zsi/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/.conda/envs/zsi/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "~/.conda/envs/zsi/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['~/.conda/envs/zsi/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/zsi/65_15/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py', '--launcher', 'pytorch']' died with <Signals.SIGSEGV: 11>.
~/.conda/envs/zsi/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
```

Then I try to run `python tools/train.py configs/zsi/65_15/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py`. 

```
unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=4.57s)
creating index...
index created!
2021-09-03 15:33:55,199 - INFO - workflow: [('train', 1)], max: 12 epochs
Segmentation fault (core dumped)
```

Any idea why? Thanks!!

**Comment by brianbt** [comment]
Ok it turns out you need a GCC>4.8
