### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by harrytrinh96** [zhengye1995/Zero-shot-Instance-Segmentation#8]
Hi, There is a problem that i face frequently, which is `RuntimeError: CUDA error: no kernel image is available for execution on the device`. I dont know why it often occurred, though I was using the exact environment versions like yours (cuda, cuddnn, mmcv, mmdet, etc). Do you know why?
```
Traceback (most recent call last):
  File "./tools/train.py", line 118, in <module>
    main()
  File "./tools/train.py", line 114, in main
    logger=logger)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/apis/train.py", line 192, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/models/detectors/base.py", line 117, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/models/detectors/zero_shot_two_stage.py", line 179, in forward_train
    x = self.extract_feat(img)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/models/detectors/zero_shot_two_stage.py", line 105, in extract_feat
    x = self.backbone(img)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/merge/Harry/instance_seg/ZSI/mmdet/models/backbones/resnet.py", line 525, in forward
    x = self.relu(x)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 99, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/merge/anaconda3/envs/zsi/lib/python3.7/site-packages/torch/nn/functional.py", line 941, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

```

I tested cuda on python, it worked fine. That means there was an issue with ZSI, not because my setup environment.

```
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.rand(10).to("cuda")

tensor([0.8508, 0.1020, 0.9818, 0.8558, 0.5624, 0.0784, 0.0054, 0.5591, 0.3068,
        0.6484], device='cuda:0')
>>> 
>>> torch.cuda.device_count()
4
>>> torch.cuda.is_available()
True
>>> 

```

**Comment by zhengye1995** [comment]
Hi, what architecture for your GPUs and which torch version in your environment?

It seems that the error occurred when running torch.relu_ operation which is caused by torch. (my torch version in this repo is 1.1.0, it may not works with RTX 30 GPU.)

Please check whether torch.relu_ can run successfully in your environment.

**Comment by harrytrinh96** [comment]
Thanks for your quick response. Here are my environment setups: 
```
torch                  1.1.0
cudatoolkit               10.0.130                   
torchvision            0.3.0
mmcv                   0.2.14
cuda                     10.2
```
running on NVIDIA RTX 3090 GPUs.
I tried to run with `torch.relu_` in my environment, it worked fine.
```
>>> import torch
>>> input = torch.randn(2).unsqueeze(0)
>>> torch.nn.functional.relu_(input)
tensor([[1.3448, 1.0200]])
```
 Then do you know what caused my problem?

**Comment by zhengye1995** [comment]
You should test relu_ in gpu but not in cpu, please try:
```
import torch
input = torch.randn(2).unsqueeze(0).cuda()
torch.nn.functional.relu_(input)
```

**Comment by harrytrinh96** [comment]
Hmmm it worked fine...
```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
4
>>> torch.version.cuda
'10.0.130'
>>> 
>>> input = torch.randn(2).unsqueeze(0).cuda()
>>> torch.nn.functional.relu_(input)
tensor([[0.0000, 1.1485]], device='cuda:0')

```

**Comment by zhengye1995** [comment]
Using RTX 3090 in cuda10 environment does often produce some strange errors so I just use cuda11 for RTX 3090.

I used P40 and 2080Ti in this repo, they all work well with cuda 10.

So, I am curious did you build torch1.1.0 with cuda10 in RTX3090 from source code successfully?

**Comment by harrytrinh96** [comment]
Thanks.
No, I installed torch 1.1.0 through conda.

**Comment by WindFall-wyx** [comment]
> Thanks. No, I installed torch 1.1.0 through conda.

How did you solve this problem？
